# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
